#' Get Sample Parameters for Simulation
#'
#' Returns sample parameters for a 9-node symptom network based on the referenced paper.
#' @return A list with beta, alpha_self, delta, sigma.
#' @export
get_sample_parameters <- function() {
  list(
    beta = c(-1.01, -0.52, -0.53, -1.01, -0.82, -0.52, -0.75, -1.10, -0.80),
    alpha_self = rep(0.1, 9),
    delta = rep(9, 9),
    sigma = rep(0.14, 9)
  )
}

#' Plot Symptom Dynamics
#'
#' Plots symptom intensities over time.
#' @param S A matrix from simulate_dynamics (time x symptoms).
#' @export
#' @importFrom grDevices rainbow
#' @importFrom graphics legend matplot
plot_symptom_dynamics <- function(S) {
  matplot(S, type = "l", lty = 1, col = rainbow(ncol(S)),
          xlab = "Time Steps", ylab = "Symptom Level", main = "Symptom Dynamics")
  legend("topright", legend = paste0("S", seq_len(ncol(S))), col = rainbow(ncol(S)), lty = 1)
}

#' Simulate from Directed Network Output
#'
#' Runs dynamics simulation from a network generated by generate_directed_networks.
#' @param network A single directed adjacency matrix.
#' @param params A list from get_sample_parameters().
#' @param t_max Maximum time.
#' @param dt Time step size.
#' @return Matrix of symptom trajectories.
#' @export
simulate_from_network <- function(network, params, t_max = 100, dt = 0.1) {
  simulate_dynamics(
    adj_matrix = network,
    beta = params$beta,
    alpha_self = params$alpha_self,
    delta = params$delta,
    sigma = params$sigma,
    t_max = t_max,
    dt = dt
  )
}
